WZK.Admin/Models/Task/ModifyTask.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WZK.Admin.Models.Task
{
    public class ModifyTask
    {
        /// <summary>
        /// 编号
        /// </summary>
        public System.Guid Id { get; set; }
        /// <summary>
        /// 任务名称
        /// </summary>
        [Display(Name = "任务名称")]
        [Required(ErrorMessage = "{0}不能为空")]
        [StringLength(25, ErrorMessage = "{0}长度不能超过25个字符")]
        public string TaskName { get; set; }
        /// <summary>
        /// 任务描述
        /// </summary>
        [Display(Name = "任务描述")]
        [Required(ErrorMessage = "{0}不能为空")]
        [StringLength(250, ErrorMessage = "{0}长度不能超过250个字符")]
        public string TaskDesc { get; set; }
        /// <summary>
        /// 任务类型
        /// </summary>
        public int TaskType { get; set; }
        /// <summary>
        /// 任务模板编号
        /// </summary>
        public System.Guid TaskTemplateId { get; set; }
        /// <summary>
        /// 任务模板名称
        /// </summary>
        [Required(ErrorMessage = "请选择任务模板")]
        public string TemplateName { get; set; }
        /// <summary>
        /// 任务开始时间
        /// </summary>
        [Display(Name ="任务开始时间")]
        [Required(ErrorMessage = "{0}不能为空")]
        
        public System.DateTime StartTime { get; set; } = DateTime.Now.AddMinutes(30);
        /// <summary>
        /// 执行周期:单位分钟  0-无周期，任务只执行1次，大于0 - n分钟执行一次
        /// </summary>
        [Required(ErrorMessage = "执行周期不能为空")]
        [RegularExpression("^\\d*$", ErrorMessage = "请输入数字,且不能为小数或负数")]
        [Range(0, 10080, ErrorMessage = "请输入0-10080以内数字")]
        public int ExecuteCycle { get; set; } = 0;
        /// <summary>
        /// 需要执行的次数：0-无限次，大于0-n次
        /// </summary>
        [Required(ErrorMessage = "需要执行的次数不能为空")]
        [RegularExpression("^\\d*$", ErrorMessage = "请输入数字,且不能为小数或负数")]
        [Range(0, 10000, ErrorMessage = "请输入0-10000以内数字")]
        public int ExecuteTimes { get; set; } = 1;
        /// <summary>
        /// 是否完成：0-未完成，1-已完成
        /// </summary>
        public int IsComplete { get; set; } = 0;
        /// <summary>
        /// 录入人
        /// </summary>
        public System.Guid InputUser { get; set; }
        /// <summary>
        /// 录入时间
        /// </summary>
        public System.DateTime InsertTime { get; set; } = DateTime.Now;
        /// <summary>
        /// 修改人
        /// </summary>
        public Nullable<System.Guid> UpdateUser { get; set; }
        /// <summary>
        /// 修改时间
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}

WZK.Admin/Models/Task/ModifyTaskDetail.cs
using MvcValidation.Extension;
using System;
using System.ComponentModel.DataAnnotations;

namespace WZK.Admin.Models.Task
{
    public class ModifyTaskDetail
    {
        /// <summary>
        /// 手机编号 信息 （以多个以^分隔）
        /// </summary>
        [Required(ErrorMessage = "请选择任务手机")]
        public string Param { get; set; }
        /// <summary>
        /// 任务编号
        /// </summary>
        [NotEqualTo("GuidEmpty", ErrorMessage = "任务信息错误")]
        public Guid TaskId { get; set; }
        /// <summary>
        /// 验证 Guid.Empty
        /// </summary>
        public Guid GuidEmpty { get; set; } = Guid.Empty;
    }
}

WZK.Admin/Controllers/LocationController.cs
using System;
using System.Web.Mvc;
using WZK.Business.Admin;
using WZK.Common;
using WZK.Entity;
using WZK.Business.Admin.Tool;
using WZK.Admin.Models.Location;
using System.Collections.Generic;

namespace WZK.Admin.Controllers
{
    public class LocationController : BaseController
    {
        LocationMgt manage = new LocationMgt();

        #region 定位列表
        /// <summary>
        /// 定位列表
        /// </summary>
        /// <returns></returns>
        /// <remarks>add by dingyong,2017-05-18 19:42:14 </remarks>
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 定位列表数据
        /// </summary>
        /// <param name="id">页码</param>
        /// <param name="title">定位标题</param>
        /// <param name="address">定位地址</param>
        /// <returns></returns>
        public ActionResult _Index(int id, string title,string address)
        {
            ViewBag.List = manage.GetLocationList(title,address,id);
            return View();
        }
        #endregion

        #region 定位列表(任务管理)
        /// <summary>
        /// 定位列表
        /// </summary>
        /// <returns></returns>
        /// <remarks>add by dingyong,2017-05-18 19:42:14 </remarks>
        public ActionResult LocationList()
        {
            return View();
        }
        /// <summary>
        /// 定位列表数据
        /// </summary>
        /// <param name="id">页码</param>
        /// <param name="title">定位标题</param>
        /// <param name="address">定位地址</param>
        /// <returns></returns>
        public ActionResult _LocationList(int id, string title, string address)
        {
            ViewBag.List = manage.GetLocationList(title, address, id);
            return View();
        }
        #endregion

        #region  定位详情
        /// <summary>
        ///  定位详情
        /// </summary>
        /// <param name="id">朋友圈模板编号</param>
        /// <returns></returns>
        /// <remarks>add by dingyong,2017-05-18 19:42:14 </remarks>
        public ActionResult LocationDetail()
        {
               ViewBag.name = "新增";
               return View(new ModifyLocation());
        }
        #endregion

        #region 修改定位信息
        /// <summary>
        /// 修改定位信息
        /// </summary>
        /// <param name="model">定位信息</param>
        /// <returns></returns>
        /// <remarks>add by dingyong,2017-05-18 19:42:14 </remarks>
        public ActionResult ModifyLocationInfo(ModifyLocation model)
        {
            if (ModelState.IsValid)
            {
                ResultInfo info = new ResultInfo();
                //新增
                info = manage.AddLocation(RoleName, ModelMapping.ChangeModel<ModifyLocation, Location>(model), this.UserId);
                return Json(info);
            }
            return this.GetAjaxErrorInfo();
        }
        #endregion

        #region 删除定位信息
        /// <summary>
        /// 删除定位信息
        /// </summary>
        /// <param name="Id">定位编号.</param>
        /// <returns>ActionResult.</returns>
        /// <remarks>add by dingyong,2017-05-18 19:42:14  </remarks>
        [HttpPost]
        public ActionResult DelLocation(Guid id)
        {
            ResultInfo info = manage.DelLocation(id, RoleName, UserId);
            return Json(info);
        }
        #endregion
    }
}

WZK.Admin/Controllers/MomentsController.cs
using System;
using System.Web.Mvc;
using WZK.Business.Admin;
using WZK.Common;
using WZK.Entity;
using WZK.Business.Admin.Tool;
using WZK.Admin.Models.Moments;
using System.Collections.Generic;

namespace WZK.Admin.Controllers
{
    public class MomentsController : BaseController
    {
        MomentsMgt manage = new MomentsMgt();

        #region 朋友圈模板列表
        /// <summary>
        /// 朋友圈模板列表
        /// </summary>
        /// <returns></returns>
        /// <remarks>add by dingyong,2017-05-18 19:42:14 </remarks>
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 朋友圈模板列表数据
        /// </summary>
        /// <param name="id">页码</param>
        /// <param name="title">标题</param>
        /// <returns></returns>
        public ActionResult _Index(int id, string title)
        {
            ViewBag.List = manage.GetMomentsList(title, id);
            return View();
        }
        #endregion

        #region 朋友圈模板列表(任务管理)
        /// <summary>
        /// 朋友圈模板列表
        /// </summary>
        /// <returns></returns>
        /// <remarks>add by dingyong,2017-05-18 19:42:14 </remarks>
        public ActionResult MomentsList()
        {
            return View();
        }
        /// <summary>
        /// 朋友圈模板列表数据
        /// </summary>
        /// <param name="id">页码</param>
        /// <param name="title">标题</param>
        /// <returns></returns>
        public ActionResult _MomentsList(int id, string title)
        {
            ViewBag.List = manage.GetMomentsList(title, id);
            return View();
        }
        #endregion

        #region  朋友圈模板详情
        /// <summary>
        ///  朋友圈模板详情
        /// </summary>
        /// <param name="id">朋友圈模板编号</param>
        /// <returns></returns>
        /// <remarks>add by dingyong,2017-05-18 19:42:14 </remarks>
        public ActionResult MomentsDetail(Guid? id)
        {
            if (id == null)
            {
                ViewBag.name = "新增";
                return View(new ModifyMoments());
            }
            else
            {
                ViewBag.name = "详情";
                var info = manage.GetMoments(id.Value);
                return View(ModelMapping.ChangeModel<MomentsTemplate, ModifyMoments>(info.ReturnObject));
            }
        }
        #endregion

        #region 修改朋友圈模板信息
        /// <summary>
        /// 修改朋友圈模板信息
        /// </summary>
        /// <param name="model">朋友圈模板信息</param>
        /// <returns></returns>
        /// <remarks>add by dingyong,2017-05-18 19:42:14 </remarks>
        public ActionResult ModifyMomentsInfo(ModifyMoments model)
        {
            if (ModelState.IsValid)
            {
                ResultInfo info = new ResultInfo();
                //新增
                if (model.Id == Guid.Empty)
                {
                    info = manage.AddMoments(RoleName, ModelMapping.ChangeModel<ModifyMoments, MomentsTemplate>(model), this.UserId);
                }
                //修改
                else
                {
                    info = manage.ModifyMoments(RoleName, ModelMapping.ChangeModel<ModifyMoments, MomentsTemplate>(model), UserId);
                }
                return Json(info);
            }
            return this.GetAjaxErrorInfo();
        }
        #endregion

        #region 删除朋友圈模板信息
        /// <summary>
        /// 删除朋友圈模板信息
        /// </summary>
        /// <param name="Id">朋友圈模板编号.</param>
        /// <returns>ActionResult.</returns>
        /// <remarks>add by dingyong,2017-05-18 19:42:14  </remarks>
        [HttpPost]
        public ActionResult DelMoments(Guid id)
        {
            ResultInfo info = manage.DelMoments(id, RoleName, UserId);
            return Json(info);
        }
        #endregion
    }
}

WZK.Admin/Controllers/ScriptController.cs
using System;
using System.Web.Mvc;
using WZK.Business.Admin;
using WZK.Common;
using WZK.Entity;
using WZK.Business.Admin.Tool;
using WZK.Admin.Models.Script;
using System.Collections.Generic;

namespace WZK.Admin.Controllers
{
    public class ScriptController : BaseController
    {
        ScriptMgt manage = new ScriptMgt();

        #region 脚本列表
        /// <summary>
        /// 脚本列表
        /// </summary>
        /// <returns></returns>
        /// <remarks>add by dingyong,2017-05-18 19:42:14 </remarks>
        public ActionResult Index()
        {
            //适配App
            ViewBag.AppList = EnumTool.ToSelectList(typeof(EApp));
            List<SelectListItem> mtList = new List<SelectListItem>();
            List<SelectListItem> dpiList = new List<SelectListItem>();
            var types = new MobileModelMgt().GetIMobileModelListAll();
            mtList.Add(new SelectListItem { Text = "--请选择--", Value = Guid.Empty.ToString() });
            dpiList.Add(new SelectListItem { Text = "--请选择--", Value = ""});
            foreach (MobileTypes mt in types.ReturnList)
            {
                mtList.Add(new SelectListItem { Text = mt.Name, Value = mt.Id.ToString() });
                dpiList.Add(new SelectListItem { Text = mt.DPI, Value = mt.DPI });
            }
            //手机型号
            ViewBag.MobileTypes = mtList;
            //手机分辨率
            ViewBag.DpiList = dpiList;
            return View();
        }
        /// <summary>
        /// 脚本列表数据
        /// </summary>
        /// <param name="id">页码</param>
        /// <param name="name">脚本名称</param>
        /// <param name="app">适配App</param>
        /// <param name="dpi">适配分辨率率</param>
        /// <param name="mType">适配手机型号</param>
        /// <returns></returns>
        public ActionResult _Index(int id, string name, string app, string dpi, Guid mType)
        {
            ViewBag.List = manage.GetScriptList(name,app,dpi,mType,id);
            return View();
        }
        #endregion

        #region 脚本列表(任务管理)
        /// <summary>
        /// 脚本列表
        /// </summary>
        /// <returns></returns>
        /// <remarks>add by dingyong,2017-05-18 19:42:14 </remarks>
        public ActionResult ScriptList()
        {
            //适配App
            ViewBag.AppList = EnumTool.ToSelectList(typeof(EApp));
            List<SelectListItem> mtList = new List<SelectListItem>();
            List<SelectListItem> dpiList = new List<SelectListItem>();
            var types = new MobileModelMgt().GetIMobileModelListAll();
            mtList.Add(new SelectListItem { Text = "--请选择--", Value = Guid.Empty.ToString() });
            dpiList.Add(new SelectListItem { Text = "--请选择--", Value = "" });
            foreach (MobileTypes mt in types.ReturnList)
            {
                mtList.Add(new SelectListItem { Text = mt.Name, Value = mt.Id.ToString() });
                dpiList.Add(new SelectListItem { Text = mt.DPI, Value = mt.DPI });
            }
            //手机型号
            ViewBag.MobileTypes = mtList;
            //手机分辨率
            ViewBag.DpiList = dpiList;
            return View();
        }
        /// <summary>
        /// 脚本列表数据
        /// </summary>
        /// <param name="id">页码</param>
        /// <param name="name">脚本名称</param>
        /// <param name="app">适配App</param>
        /// <param name="dpi">适配分辨率率</param>
        /// <param name="mType">适配手机型号</param>
        /// <returns></returns>
        public ActionResult _ScriptList(int id, string name, string app, string dpi, Guid mType)
        {
            ViewBag.List = manage.GetScriptList(name, app, dpi, mType, id);
            return View();
        }
        #endregion

        #region 脚本信息详情
        /// <summary>
        /// 脚本信息详情
        /// </summary>
        /// <param name="id">脚本编号</param>
        /// <returns></returns>
        /// <remarks>add by dingyong,2017-05-18 19:42:14 </remarks>
        public ActionResult ScriptDetail(Guid? id)
        {
            List<SelectListItem> AppList = new List<SelectListItem>();
            Array _enumValues = System.Enum.GetValues(typeof(EApp));
            AppList.Add(new SelectListItem { Text ="--请选择--", Value = "" });
            foreach (object value in _enumValues)
            {
                AppList.Add(new SelectListItem
                {
                    Text =EnumTool.GetDesc((System.Enum)value),
                    Value = EnumTool.GetDesc((System.Enum)value)
                });
            }
            //适配App
            ViewBag.AppList = AppList;
            List<SelectListItem> mtList = new List<SelectListItem>();
            var types = new MobileModelMgt().GetIMobileModelListAll();
            mtList.Add(new SelectListItem { Text = "--请选择--", Value = Guid.Empty.ToString() });
            foreach (MobileTypes mt in types.ReturnList)
            {
                mtList.Add(new SelectListItem { Text = mt.Name + "(" + mt.DPI + ")", Value = mt.Id.ToString() });
            }
            //手机型号
            ViewBag.MobileTypes = mtList;
            if (id == null)
            {
                ViewBag.name = "新增";
                return View(new ModifyScript());
            }
            else
            {
                ViewBag.name = "详情";
                var info = manage.GetScript(id.Value);
                return View(ModelMapping.ChangeModel<Script, ModifyScript>(info.ReturnObject));
            }
        }
        #endregion

        #region 修改脚本信息
        /// <summary>
        /// 修改脚本信息
        /// </summary>
        /// <param name="model">脚本信息</param>
        /// <returns></returns>
        /// <remarks>add by dingyong,2017-05-18 19:42:14 </remarks>
        public ActionResult ModifyScriptInfo(ModifyScript model)
        {
            if (ModelState.IsValid)
            {
                ResultInfo info = new ResultInfo();
                //新增
                if (model.Id == Guid.Empty)
                {
                    info = manage.AddScript(RoleName, ModelMapping.ChangeModel<ModifyScript, Script>(model), this.UserId);
                }
                //修改
                else
                {
                    info = manage.ModifyScript(RoleName, ModelMapping.ChangeModel<ModifyScript, Script>(model), UserId);
                }
                return Json(info);
            }
            return this.GetAjaxErrorInfo();
        }
        #endregion

        #region 删除脚本
        /// <summary>
        /// 删除脚本
        /// </summary>
        /// <param name="Id">脚本编号.</param>
        /// <returns>ActionResult.</returns>
        /// <remarks>add by dingyong,2017-05-18 19:42:14  </remarks>
        [HttpPost]
        public ActionResult DelScript(Guid id)
        {
            ResultInfo info = manage.DelScript(id, RoleName, UserId);
            return Json(info);
        }
        #endregion
    }
}

WZK.Admin/Views/Task/Index.cshtml
@{
    ViewBag.Title = "任务列表";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="content">
    <div id="content-header">
        <div id="breadcrumb">
            <a href="javascript:;"><i class="icon-home"></i>微智控运营管理系统</a>
            <a href="javascript:;">云控管理</a>
            <a href="javascript:;">任务管理</a>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <div class="widget-box">
                    <div class="widget-content border-top">
                        <div class="controls controls-row">
                            <label class="span1 m-wrap search-label">任务名称</label>
                            <input type="text" class="span11 m-wrap" value="" placeholder="请输入任务名称" id="name" />
                            <label class="span1 m-wrap search-label">模板名称</label>
                            <input type="text" class="span11 m-wrap" value="" placeholder="请输入模板名称" id="template" />
                            <label class="span1 m-wrap search-label">开始执行时间</label>
                            <input placeholder="请选择" type="text" id="txtTimeStar" class="span11 m-wrap" maxlength="20" style="margin-right:3px" onFocus="WdatePicker({ onpicked: function () { txtTimeEnd.focus(); }, maxDate: '#F{$dp.$D(\'txtTimeEnd\')||\'%y-%M-%d\'}', dateFmt: 'yyyy-MM-dd HH:mm:ss' })" />
                            <label id="line-span">-</label>
                            <input placeholder="请选择" type="text" id="txtTimeEnd" class="span11 m-wrap" maxlength="20" onFocus="WdatePicker({ minDate: '#F{$dp.$D(\'txtTimeStar\')}', dateFmt: 'yyyy-MM-dd HH:mm:ss' })" />
                            <label class="span1 m-wrap search-label">任务类型</label>
                            @Html.DropDownList("ddTaskType", ViewBag.TaskType as List<SelectListItem>, new { @class = "span1 m-wrap" })
                           
                            <button class="span0 m-wrap  btn btn-success btn-mini" type="button" id="btnSearch">查询</button>
                            @if (WZK.Admin.Common.RightInfo.GetRightInfo().CanUse("Task", "ModifyTaskInfo"))
                            {
                                <button class="span0 m-wrap  btn btn-success btn-mini" type="button" id="btnAdd">新增</button>
                            }
                            <input type="hidden" id="hdIndex" value="1" />
                        </div>
                    </div>
                    <div id="container">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    @Scripts.Render("~/Scripts/My97DatePicker/WdatePicker.js", "~/Scripts/Page/showpage.js")
    <script type="text/javascript">
        $(function () {
            //初始化列表数据
            getPageData($("#hdIndex").val());
            //搜索
            $('#btnSearch').click(function (e) {
                getPageData(1);
            });
            //新增
            $('#btnAdd').click(function () {
                location.href = "/Task/TaskDetail";
            });
            $("#ddTaskType").change(function () {
                getPageData(1);//下拉框值变换事件
            });
        });
        //获取分页数据
        function getPageData(index) {
            $.get("/Task/_Index/" + index + "?random=" + Math.random(), {
                name: $("#name").val().trim(),
                startTime: $("#txtTimeStar").val(),
                endTime: $("#txtTimeEnd").val(),
                type: $("#ddTaskType").val(),
                template: $("#template").val()
            }, function (data) {
                $('#container').html(data);
            });
        }
    </script>
}

WZK.Admin/Views/Task/TaskDetail.cshtml
@model WZK.Admin.Models.Task.ModifyTask
@{
    ViewBag.Title = "云控管理-任务管理-" + @ViewBag.name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="content">
    <div id="content-header">
        <div id="breadcrumb">
            <a href="javascript:;"><i class="icon-home"></i>微智控运营管理系统</a>
            <a href="javascript:;">云控管理</a>
            <a href="@Url.Action("Index","Task")">任务管理</a>
            <a href="javascript:;">@ViewBag.name</a>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <div class="widget-box">
                    <div class="widget-content nopadding">
                        @using (Ajax.BeginForm("ModifyTaskInfo", "Task", new AjaxOptions { HttpMethod = "POST", OnSuccess = "success" }, new { @class = "form-horizontal" }))
                        {
                            <div class="control-group">
                                <label class="control-label"><span>*</span>任务名称：</label>
                                <div class="controls">
                                    @Html.TextBoxFor(m => m.TaskName)
                                    @Html.ValidationMessageFor(m => m.TaskName)
                                    @Html.HiddenFor(m => m.Id)
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label"><span>*</span>任务描述：</label>
                                <div class="controls">
                                    @Html.TextAreaFor(m => m.TaskDesc, 10, 40, new { @style = "width:320px" })
                                    @Html.ValidationMessageFor(m => m.TaskDesc)
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label"><span>*</span>任务类型：</label>
                                <div class="controls">
                                    @Html.DropDownListFor(m => m.TaskType, ViewBag.LTaskType as List<SelectListItem>)
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">任务模板：</label>
                                <div class="controls">
                                    @Html.TextBoxFor(m => m.TemplateName, new { @readonly = "readonly" })
                                    <input type="button" value="选择模板" class="btn btn-info span1  mrl" id="btnChoice" />
                                    @Html.HiddenFor(m => m.TaskTemplateId)
                                    @Html.ValidationMessageFor(m => m.TemplateName)
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label"><span>*</span>任务开始时间：</label>
                                <div class="controls">
                                    @Html.TextBoxFor(m => m.StartTime, new { @onFocus = "WdatePicker({minDate:'%y/%M/%d %H:(%m+30):%s',dateFmt: 'yyyy/MM/dd HH:mm:ss' })" })
                                    @Html.ValidationMessageFor(m => m.StartTime)
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label"><span>*</span>执行周期：</label>
                                <div class="controls">
                                    @Html.TextBoxFor(m => m.ExecuteCycle)
                                    <span> &nbsp; 执行周期：m 单位分钟 (m=0 ->无周期,且只执行1次，m>0 -> m分钟执行一次)</span>
                                    @Html.ValidationMessageFor(m => m.ExecuteCycle)
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label">执行次数：</label>
                                <div class="controls">
                                  @Html.TextBoxFor(m => m.ExecuteTimes)
                                    <span> &nbsp; 需要执行的次数：n (n=0 -> 无限次，n>0 -> 执行n次)</span>
                                  @Html.ValidationMessageFor(m => m.ExecuteTimes)
                                </div>
                            </div>
                            <div class="form-actions">
                                <label id="tdMsg"></label>
                                <input type="submit" value="保存" class="btn btn-info" />
                                <input type="button" value="返回" class="btn" onclick="javascript: history.go(-1);" />
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
  @Scripts.Render("~/Scripts/My97DatePicker/WdatePicker.js")
    <script type="text/javascript">
        $(function () {
            $("form").data("validator").settings.ignore = "";
            $("#btnChoice").click(function () {
                var type = Math.floor($("#TaskType").val());
                var requestUrl="", title="";
                if (type == 1) {//执行脚本
                    requestUrl = '@Url.Action("ScriptList", "Script")';
                    title = "选择脚本模板";
                } else if (type == 2) {//自动回复
                    requestUrl = '@Url.Action("ReplyList", "AutoReply")';
                    title = "选择自动回复模板";
                } else if (type == 3) {//发朋友圈
                    requestUrl = '@Url.Action("MomentsList", "Moments")';
                    title = "选择朋友圈模板";
                } else if (type == 4) {//定位
                    requestUrl = '@Url.Action("LocationList", "Location")';
                    title = "选择定位模板";
                }
                $.get(requestUrl, {}, function (view) {
                    layer.open({
                        type: 1,
                        title: title,
                        skin: 'layui-layer-rim', //加上边框
                        area: ['1024px', '670px'], //宽高
                        content: view,
                        btn: ['取消'],
                        yes: function () {
                            layer.closeAll();
                        }
                    });
                });
            });
            $("body").on('click', '.js-choice', function () {
                var $this = $(this);
                $("#TaskTemplateId").val($this.data("id"));
                $("#TemplateName").val($this.data("name"));
                layer.closeAll();
            });
        });
        function success(data) {
            if (data.IsPass) {
                layer.msg("保存成功", { time: 1000,icon:1}, function () {
                    window.location.href = "/Task/Index";
                });
            } else {
                $("#tdMsg").text(data.Desc);
            }
        }
    </script>
}

WZK.Admin/Views/Task/_Index.cshtml
@{
    Layout = null;
}
<div class="widget-content nopadding">
    <table class="table table-bordered table-striped with-check table-hover">
        <thead>
            <tr>
                <th class="w15">任务名称</th>
                <th class="w20">任务描述</th>
                <th class="w8">任务类型</th>
                <th class="w15">模板名称</th>
                <th class="w12">开始执行时间</th>
                <th class="w7">录入人</th>
                <th class="w12">录入时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            @if (ViewBag.List.Count == 0)
            {
                <tr class="gradeA">
                    <td colspan="8">未查询到相关数据</td>
                </tr>
            }
            else
            {
                var ck = WZK.Admin.Common.RightInfo.GetRightInfo().CanUse("Task", "TaskDetail");
                var zd = WZK.Admin.Common.RightInfo.GetRightInfo().CanUse("Task", "AddTaskDetail");
                foreach (WZK.Models.admin.MTask item in ViewBag.List.ReturnList)
                {
                    <tr class="gradeA">
                        <td>@item.TaskName</td>
                        <td>@item.TaskDesc</td>
                        <td>@EnumTool.GetDesc((ETaskType)item.TaskType)</td>
                        <td>@item.TemplateName</td>
                        <td>@item.StartTime.ToString("yyyy-MM-dd HH:mm:ss")</td>
                        <td>@item.InputUser</td>
                        <td>@item.InsertTime.ToString("yyyy-MM-dd HH:mm:ss")</td>
                        <td>
                            <div class="xc_wrap">
                                @if (ck)
                                {
                                    @Html.ActionLink("查看", "TaskDetail", new { item.Id }, new { @class = "btn btn-info xc btn-mini" })
                                }

                                @if (zd)
                                {
                                    @Html.ActionLink("指定手机", "TaskDetailList", new { item.Id }, new { @class = "btn btn-primary xc btn-mini" })
                                }
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
@if ((int)ViewBag.List.Count > WZK.Common.ConfigData.PageConfig.PageSize)
{
    <div class="pagination page">
        @Html.ShowPageNavigate((int)ViewBag.List.Count, WZK.Common.ConfigData.PageConfig.PageSize)
    </div>
}