WZK.Admin/Models/IDCS/ModifyIDCInfo.cs
using WZK.Admin.Common;
using System;
using System.ComponentModel.DataAnnotations;

namespace WZK.Admin.Models.IDCS
{
    public class ModifyIDCInfo
    {
        /// <summary>
        /// 编号
        /// </summary>
        public System.Guid Id { get; set; }
        /// <summary>
        /// 机房名称
        /// </summary>
        [Required(ErrorMessage = "机房名称不能为空")]
        [StringLength(20, ErrorMessage = "机房名称长度不能超过20个字符")]
        public string Name { get; set; }
        /// <summary>
        /// 机房地址
        /// </summary>
        [Required(ErrorMessage = "机房地址不能为空")]
        [StringLength(120, ErrorMessage = "机房地址长度不能超过120个字符")]
        public string Address { get; set; }
        /// <summary>
        /// 录入人
        /// </summary>
        public System.Guid InputUser { get; set; }
        /// <summary>
        /// 录入时间
        /// </summary>
        public System.DateTime InsertTime { get; set; } = DateTime.Now;
        /// <summary>
        /// 修改人
        /// </summary>
        public Nullable<System.Guid> UpdateUser { get; set; }
        /// <summary>
        /// 更新时间
        /// </summary>
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}

WZK.Admin/Controllers/IDCSController.cs
using System;
using System.Web.Mvc;
using WZK.Business.Admin;
using WZK.Common;
using WZK.Entity;
using WZK.Business.Admin.Tool;
using WZK.Admin.Models.IDCS;

namespace WZK.Admin.Controllers
{
    public class IDCSController : BaseController
    {
        IDCSMgt manage = new IDCSMgt();

        #region 机房列表
        /// <summary>
        /// 机房列表
        /// </summary>
        /// <returns></returns>
        /// <remarks>author:dingyong date:2017-05-12</remarks>
        public ActionResult Index()
        {
            return View();
        }
        /// <summary>
        /// 机房列表数据
        /// </summary>
        /// <param name="id">页码</param>
        /// <param name="name">机房名称</param>
        /// <returns></returns>
        public ActionResult _Index(int id,string name)
        {
            ViewBag.List = manage.GetIDCSList(name, id);
            return View();
        }
        #endregion

        #region 机房信息详情
        /// <summary>
        /// 机房信息详情
        /// </summary>
        /// <param name="id">机房编号</param>
        /// <returns></returns>
        /// <remarks>author:dingyong date:2017-05-12</remarks>
        public ActionResult IDCDetail(Guid? id)
        {
            if (id == null)
            {
                ViewBag.name = "新增";
                return View(new ModifyIDCInfo());
            }
            else
            {
                ViewBag.name = "详情";
                var info = manage.GetIDCS(id.Value);
                return View(ModelMapping.ChangeModel<IDCS, ModifyIDCInfo>(info.ReturnObject));
            }
        }
        #endregion

        #region 修改机房信息
        /// <summary>
        /// 修改机房信息
        /// </summary>
        /// <param name="model">机房信息</param>
        /// <returns></returns>
        /// <remarks>author:dingyong date:2016-07-05</remarks>
        public ActionResult ModifyIDCInfo(ModifyIDCInfo model)
        {
            if (ModelState.IsValid)
            {
                ResultInfo info = new ResultInfo();
                //新增
                if (model.Id == Guid.Empty)
                {
                    info = manage.AddIDCS(RoleName,ModelMapping.ChangeModel<ModifyIDCInfo, IDCS>(model),this.UserId);
                }
                //修改
                else
                {
                    info = manage.ModifyIDCS(RoleName,ModelMapping.ChangeModel<ModifyIDCInfo, IDCS>(model), UserId);
                }
                return Json(info);
            }
            return this.GetAjaxErrorInfo();
        }
        #endregion

        #region 删除机房
        /// <summary>
        /// 删除机房
        /// </summary>
        /// <param name="Id">机房编号.</param>
        /// <returns>ActionResult.</returns>
        /// <remarks>add by dingyong,2016-09-13 15:17:45 </remarks>
        [HttpPost]
        public ActionResult DeleteIDC(Guid id)
        {
            ResultInfo info = manage.DelIDCS(id, RoleName, UserId);
            return Json(info);
        }
        #endregion

    }
}

WZK.Admin/Views/IDCS/IDCDetail.cshtml
@model WZK.Admin.Models.IDCS.ModifyIDCInfo
@{
    ViewBag.Title = "云控管理-机房管理-" + @ViewBag.name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="content">
    <div id="content-header">
        <div id="breadcrumb">
            <a href="javascript:;"><i class="icon-home"></i>微智控运营管理系统</a>
            <a href="javascript:;">云控管理</a>
            <a href="@Url.Action("Index","IDCS")">机房管理</a>
            <a href="javascript:;">@ViewBag.name</a>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <div class="widget-box">
                    <div class="widget-content nopadding">
                        @using (Ajax.BeginForm("ModifyIDCInfo", "IDCS", new AjaxOptions { HttpMethod = "POST", OnSuccess = "success" }, new { @class = "form-horizontal" }))
                        {
                            <div class="control-group">
                                <label class="control-label"><span>*</span>机房名：</label>
                                <div class="controls">
                                    @Html.TextBoxFor(m => m.Name)
                                    @Html.ValidationMessageFor(m => m.Name)
                                    @Html.HiddenFor(m => m.Id)
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label"><span>*</span>机房地址：</label>
                                <div class="controls">
                                    @Html.TextAreaFor(m => m.Address,new { rows = "4" })
                                    @Html.ValidationMessageFor(m => m.Address)
                                </div>
                            </div>
                            <div class="form-actions">
                                <label id="tdMsg"></label>
                                <input type="submit" value="保存" class="btn btn-info" />
                                <input type="button" value="返回" class="btn" onclick="javascript: history.go(-1);" />
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    <script type="text/javascript">
        $(function () {
            $("form").data("validator").settings.ignore = "";
        });
        function success(data) {
            if (data.IsPass) {
                layer.msg("保存成功", { time: 1000,icon:1}, function () {
                    window.location.href = "/IDCS/Index";
                });
            } else {
                $("#tdMsg").text(data.Desc);
            }
        }
    </script>
}

WZK.Admin/Views/IDCS/Index.cshtml
@{
    ViewBag.Title = "机房列表";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="content">
    <div id="content-header">
        <div id="breadcrumb">
            <a href="javascript:;"><i class="icon-home"></i>微智控运营管理系统</a>
            <a href="javascript:;">云控管理</a>
            <a href="javascript:;">机房管理</a>
        </div>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <div class="span12">
                <div class="widget-box">
                    <div class="widget-content border-top">
                        <div class="controls controls-row">
                            <label class="span1 m-wrap search-label">机房名/地址</label>
                            <input type="text" class="span2 m-wrap" value="" placeholder="请输入机房名/地址" id="name"/>
                            <button class="span1 m-wrap  btn btn-success" type="button" id="btnSearch">查询</button>
                            @if (WZK.Admin.Common.RightInfo.GetRightInfo().CanUse("IDCS", "ModifyIDCInfo"))
                            {
                                <button class="span1 m-wrap  btn btn-success" type="button" id="btnAdd">新增</button>
                            }
                            <input type="hidden" id="hdIndex" value="1" />
                        </div>
                    </div>
                    <div id="container">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section scripts{
    @Scripts.Render("~/Scripts/Page/showpage.js")
    <script type="text/javascript">
        $(function () {
            //初始化列表数据
            getPageData($("#hdIndex").val());
            //搜索
            $('#btnSearch').click(function (e) {
                getPageData(1);
            });
            //新增
            $('#btnAdd').click(function () {
                location.href = "/IDCS/IDCDetail";
            });
        });
        //获取分页数据
        function getPageData(index) {
            $.get("/IDCS/_Index/" + index + "?random=" + Math.random(), {
                name: $("#name").val().trim()
            }, function (data) {
                $('#container').html(data);
            });
        }
    </script>
}

WZK.Admin/Views/IDCS/_Index.cshtml
@{
    Layout = null;
}
<div class="widget-content nopadding">
    <table class="table table-bordered table-striped with-check table-hover">
        <thead>
            <tr>
                <th class="w20">机房名</th>
                <th class="w35">机房地址</th>
                <th class="10">录入人</th>
                <th class="15">录入时间</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            @if (ViewBag.List.Count == 0)
            {
                <tr class="gradeA">
                    <td colspan="5">未查询到相关数据</td>
                </tr>
            }
            else
            {
                var ck = WZK.Admin.Common.RightInfo.GetRightInfo().CanUse("IDCS", "IDCDetail");
                var dk = WZK.Admin.Common.RightInfo.GetRightInfo().CanUse("IDCS", "DeleteIDC");
                foreach (WZK.Models.admin.MIDCS item in ViewBag.List.ReturnList)
                {
                    <tr class="gradeA">
                        <td>@item.Name</td>
                        <td>@item.Address</td>
                        <td>@item.InputUser</td>
                        <td>@item.InsertTime.ToString("yyyy-MM-dd HH:mm:ss")</td>
                        <td>
                            <div class="xc_wrap">
                                @if (ck)
                                {
                                    @Html.ActionLink("查看", "IDCDetail", new { item.Id }, new { @class = "btn btn-info xc btn-mini" })
                                }
                              
                                @if (dk)
                                {
                                    <a href="javascript:;" data-id="@item.Id" data-name="@item.Name" class="btn btn-danger xc btn-del btn-mini">删除</a>
                                }
                            </div>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
@if ((int)ViewBag.List.Count > WZK.Common.ConfigData.PageConfig.PageSize)
{
    <div class="pagination page">
        @Html.ShowPageNavigate((int)ViewBag.List.Count, WZK.Common.ConfigData.PageConfig.PageSize)
    </div>
}
<script type="text/javascript">
    $(function () {
        $(".btn-del").click(function () {
            var $this = $(this);
            var id = $this.data("id");
            var name = $this.data("name");
            layer.confirm('确认要删除机房<span class="deltc">“' + name + '”</span>吗？', {
                btn: ['确认', '取消'] //按钮
            }, function () {
                $.post('@Url.Action("DeleteIDC")', { id: id }, function (data) {
                    if (data.IsPass == true) {
                        layer.msg('删除成功', { icon: 1, time: 1000 }, function () {
                            location.reload(true);
                        });
                    } else {
                        layer.msg('删除失败：' + data.msg, { icon: 2 });
                    }
                });
            });
        });
    })
</script>